project:
  type: book

book:
  title: "Introduction to linear regression analysis"
  author: "Boyko Amarov"
  date: "4/11/2023"
  chapters:
    - index.qmd
    - 01-Introduction-to-R.qmd
    - 02-Statistics-Review.qmd
    - 03-Simple-Linear-Model.qmd
    - 04-Simple-ANOVA.qmd
    - 05-Hypothesis-Testing-and-CI.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
  pdf:
    documentclass: scrreprt

editor: visual
